"""Fix relationship between muscle and muscle_antagonists

Revision ID: 055af4643770
Revises: de0f17dbc9b2
Create Date: 2026-07-08 15:25:51.779770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055af4643770'
down_revision: Union[str, Sequence[str], None] = 'de0f17dbc9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'rate',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    # ### end Alembic commands ###
