"""Add new constraint to table TrainingDay

Revision ID: 20b7ed603f82
Revises: 2be69d3973dc
Create Date: 2026-07-04 17:03:20.998451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b7ed603f82'
down_revision: Union[str, Sequence[str], None] = '2be69d3973dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_workout_day_order', 'trainingday', ['workout_id', 'day_order'])
    op.alter_column('workout', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'rate',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    op.drop_constraint('uq_workout_day_order', 'trainingday', type_='unique')
    op.create_table('muscle',
    sa.Column('muscle_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('muscle_id', name=op.f('muscle_pkey'))
    )
    op.create_index(op.f('ix_muscle_name'), 'muscle', ['name'], unique=False)
    # ### end Alembic commands ###
