"""Add hashed_password column to table User

Revision ID: 3de4acaa18a7
Revises: c08e4063db38
Create Date: 2026-07-27 16:05:18.186773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de4acaa18a7'
down_revision: Union[str, Sequence[str], None] = 'c08e4063db38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_password', sa.Text(), nullable=False, server_default="hashed_password"))
    op.alter_column('workout', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'rate',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    op.drop_column('user', 'hash_password')
    # ### end Alembic commands ###
