"""Removed unique constraint on TrainingDay.day_order

Revision ID: 6384bd691d7b
Revises: 20b7ed603f82
Create Date: 2026-07-04 17:09:07.406893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6384bd691d7b'
down_revision: Union[str, Sequence[str], None] = '20b7ed603f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('trainingday_day_order_key'), 'trainingday', type_='unique')
    op.alter_column('workout', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'rate',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    op.create_unique_constraint(op.f('trainingday_day_order_key'), 'trainingday', ['day_order'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
