"""Created sets_history table, removed columns from exercisehistory: weight, sets, reps

Revision ID: 6764bc769ebf
Revises: b734555632e2
Create Date: 2026-08-20 04:26:09.468128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6764bc769ebf'
down_revision: Union[str, Sequence[str], None] = 'b734555632e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setshistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_history_id', sa.Integer(), nullable=False),
    sa.Column('set', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(precision=2), nullable=True),
    sa.Column('time_for_set', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_history_id'], ['exercisehistory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setshistory_exercise_history_id'), 'setshistory', ['exercise_history_id'], unique=False)
    op.drop_column('exercisehistory', 'sets')
    op.drop_column('exercisehistory', 'reps')
    op.drop_column('exercisehistory', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercisehistory', sa.Column('weight', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('exercisehistory', sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercisehistory', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_setshistory_exercise_history_id'), table_name='setshistory')
    op.drop_table('setshistory')
    # ### end Alembic commands ###
