"""Init DB

Revision ID: 70cb075bf6c0
Revises: 
Create Date: 2026-07-03 16:12:06.641122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70cb075bf6c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gif_url', sa.Text(), nullable=True),
    sa.Column('muscle_activation', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('login', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=True)
    op.create_table('workout',
    sa.Column('workout_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('rate', sa.Float(precision=2), nullable=False, comment='Оценка от 0 до 10'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_index(op.f('ix_workout_name'), 'workout', ['name'], unique=False)
    op.create_index(op.f('ix_workout_user_id'), 'workout', ['user_id'], unique=False)
    op.create_table('trainingday',
    sa.Column('day_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('day_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('day_id'),
    sa.UniqueConstraint('day_order')
    )
    op.create_index(op.f('ix_trainingday_workout_id'), 'trainingday', ['workout_id'], unique=False)
    op.create_table('dayexercise',
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['trainingday.day_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('day_id', 'exercise_id')
    )
    op.create_index(op.f('ix_dayexercise_day_id'), 'dayexercise', ['day_id'], unique=False)
    op.create_index(op.f('ix_dayexercise_exercise_id'), 'dayexercise', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dayexercise_exercise_id'), table_name='dayexercise')
    op.drop_index(op.f('ix_dayexercise_day_id'), table_name='dayexercise')
    op.drop_table('dayexercise')
    op.drop_index(op.f('ix_trainingday_workout_id'), table_name='trainingday')
    op.drop_table('trainingday')
    op.drop_index(op.f('ix_workout_user_id'), table_name='workout')
    op.drop_index(op.f('ix_workout_name'), table_name='workout')
    op.drop_table('workout')
    op.drop_index(op.f('ix_user_login'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
