"""Made tr_day_history fk in exercise history nullable

Revision ID: 81e0ca76843e
Revises: 6764bc769ebf
Create Date: 2026-08-20 07:29:13.035754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81e0ca76843e'
down_revision: Union[str, Sequence[str], None] = '6764bc769ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercisehistory', 'training_day_history_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('setshistory', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setshistory', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('exercisehistory', 'training_day_history_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
