"""sets history cascade

Revision ID: 8cdbdc7cb500
Revises: 93e185c3fecc
Create Date: 2026-09-08 17:08:55.065572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdbdc7cb500'
down_revision: Union[str, Sequence[str], None] = '93e185c3fecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setshistory', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.drop_constraint(op.f('setshistory_exercise_history_id_fkey'), 'setshistory', type_='foreignkey')
    op.create_foreign_key(None, 'setshistory', 'exercisehistory', ['exercise_history_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'setshistory', type_='foreignkey')
    op.create_foreign_key(op.f('setshistory_exercise_history_id_fkey'), 'setshistory', 'exercisehistory', ['exercise_history_id'], ['id'])
    op.alter_column('setshistory', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
