"""New tables ExerciseHistory and TrainingDayHistory, moved pks name to id

Revision ID: 8f7bdd225106
Revises: 3de4acaa18a7
Create Date: 2026-08-07 16:14:03.346435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7bdd225106'
down_revision: Union[str, Sequence[str], None] = '3de4acaa18a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
