"""Made tr_day_history fk in exercise history set to null after being deleted

Revision ID: 93e185c3fecc
Revises: 81e0ca76843e
Create Date: 2026-08-20 07:31:57.380299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e185c3fecc'
down_revision: Union[str, Sequence[str], None] = '81e0ca76843e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercisehistory_training_day_history_id_fkey'), 'exercisehistory', type_='foreignkey')
    op.create_foreign_key(None, 'exercisehistory', 'trainingdayhistory', ['training_day_history_id'], ['id'], ondelete='SET NULL')
    op.alter_column('setshistory', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('setshistory', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_constraint(None, 'exercisehistory', type_='foreignkey')
    op.create_foreign_key(op.f('exercisehistory_training_day_history_id_fkey'), 'exercisehistory', 'trainingdayhistory', ['training_day_history_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
