"""Deleted workout_id fk from table dayexercise

Revision ID: b734555632e2
Revises: f563f832d0d4
Create Date: 2026-08-14 10:14:02.436392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b734555632e2'
down_revision: Union[str, Sequence[str], None] = 'f563f832d0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dayexercise_workout_id'), table_name='dayexercise')
    op.drop_constraint(op.f('dayexercise_workout_id_fkey'), 'dayexercise', type_='foreignkey')
    op.drop_column('dayexercise', 'workout_id')
    op.alter_column('exercisehistory', 'weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercisehistory', 'weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('dayexercise', sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('dayexercise_workout_id_fkey'), 'dayexercise', 'workout', ['workout_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_dayexercise_workout_id'), 'dayexercise', ['workout_id'], unique=False)
    # ### end Alembic commands ###
