"""Add new column - workout_id in day_exercise

Revision ID: c08e4063db38
Revises: 055af4643770
Create Date: 2026-07-16 11:33:37.468200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08e4063db38'
down_revision: Union[str, Sequence[str], None] = '055af4643770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dayexercise', sa.Column('workout_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_dayexercise_workout_id'), 'dayexercise', ['workout_id'], unique=False)
    op.create_foreign_key(None, 'dayexercise', 'workout', ['workout_id'], ['workout_id'], ondelete='CASCADE')
    op.alter_column('workout', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'rate',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    op.drop_constraint(None, 'dayexercise', type_='foreignkey')
    op.drop_index(op.f('ix_dayexercise_workout_id'), table_name='dayexercise')
    op.drop_column('dayexercise', 'workout_id')
    # ### end Alembic commands ###
