"""Initialize muscle_antaginist and insert data into it

Revision ID: de0f17dbc9b2
Revises: 6384bd691d7b
Create Date: 2026-07-06 16:42:51.848482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de0f17dbc9b2'
down_revision: Union[str, Sequence[str], None] = '6384bd691d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    op.create_table('muscle_antagonists',
        sa.Column('muscle_id', sa.Integer(), nullable=False),
        sa.Column('muscle_antagonist_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['muscle_antagonist_id'], ['muscle.muscle_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['muscle_id'], ['muscle.muscle_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('muscle_id', 'muscle_antagonist_id')
    )
    op.create_index(op.f('ix_muscle_antagonists_muscle_antagonist_id'), 'muscle_antagonists', ['muscle_antagonist_id'], unique=False)
    op.create_index(op.f('ix_muscle_antagonists_muscle_id'), 'muscle_antagonists', ['muscle_id'], unique=False)

    muscle_antagonists = sa.table(
        'muscle_antagonists',
        sa.Column('muscle_id'),
        sa.Column('muscle_antagonist_id')
    )

    conn.execute(
        sa.insert(muscle_antagonists),
        [
            {"muscle_id": 1, "muscle_antagonist_id": 2},   # chest <-> upper_back
            {"muscle_id": 2, "muscle_antagonist_id": 1},   # upper_back <-> chest
            
            {"muscle_id": 1, "muscle_antagonist_id": 4},   # chest <-> shoulders
            {"muscle_id": 4, "muscle_antagonist_id": 1},   # shoulders <-> chest
            
            {"muscle_id": 2, "muscle_antagonist_id": 4},   # upper_back <-> shoulders
            {"muscle_id": 4, "muscle_antagonist_id": 2},   # shoulders <-> upper_back
            
            {"muscle_id": 3, "muscle_antagonist_id": 10},  # lower_back <-> abs
            {"muscle_id": 10, "muscle_antagonist_id": 3},  # abs <-> lower_back
            
            {"muscle_id": 3, "muscle_antagonist_id": 12},  # lower_back <-> quads
            {"muscle_id": 12, "muscle_antagonist_id": 3},  # quads <-> lower_back
            
            {"muscle_id": 4, "muscle_antagonist_id": 5},   # shoulders <-> traps
            {"muscle_id": 5, "muscle_antagonist_id": 4},   # traps <-> shoulders
            
            {"muscle_id": 6, "muscle_antagonist_id": 7},   # biceps <-> triceps
            {"muscle_id": 7, "muscle_antagonist_id": 6},   # triceps <-> biceps
            
            {"muscle_id": 9, "muscle_antagonist_id": 10},  # hips <-> abs
            {"muscle_id": 10, "muscle_antagonist_id": 9},  # abs <-> hips
            
            {"muscle_id": 9, "muscle_antagonist_id": 3},   # hips <-> lower_back
            {"muscle_id": 3, "muscle_antagonist_id": 9},   # lower_back <-> hips
            
            {"muscle_id": 10, "muscle_antagonist_id": 11}, # abs <-> obliques
            {"muscle_id": 11, "muscle_antagonist_id": 10}, # obliques <-> abs
            
            {"muscle_id": 12, "muscle_antagonist_id": 13}, # quads <-> hamstrings
            {"muscle_id": 13, "muscle_antagonist_id": 12}, # hamstrings <-> quads
            
            {"muscle_id": 13, "muscle_antagonist_id": 14}, # hamstrings <-> glutes
            {"muscle_id": 14, "muscle_antagonist_id": 13}, # glutes <-> hamstrings
            
            {"muscle_id": 12, "muscle_antagonist_id": 14}, # quads <-> glutes
            {"muscle_id": 14, "muscle_antagonist_id": 12}, # glutes <-> quads
            
            {"muscle_id": 15, "muscle_antagonist_id": 12}, # calves <-> quads (частично)
            {"muscle_id": 12, "muscle_antagonist_id": 15}, # quads <-> calves (частично)
        ]
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout', 'rate',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_comment='Оценка от 0 до 10',
               existing_nullable=False)
    op.drop_index(op.f('ix_muscle_antagonists_muscle_id'), table_name='muscle_antagonists')
    op.drop_index(op.f('ix_muscle_antagonists_muscle_antagonist_id'), table_name='muscle_antagonists')
    op.drop_table('muscle_antagonists')
    # ### end Alembic commands ###
