"""Fix

Revision ID: f563f832d0d4
Revises: 8f7bdd225106
Create Date: 2026-08-08 12:53:24.493359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f563f832d0d4'
down_revision: Union[str, Sequence[str], None] = '8f7bdd225106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_id', new_column_name='id')

    op.alter_column('workout', 'workout_id', new_column_name='id') 
    op.drop_constraint(op.f('workout_user_id_fkey'), 'workout', type_='foreignkey')
    op.create_foreign_key(None, 'workout', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('workout', 'rate')

    op.alter_column('trainingday', 'day_id', new_column_name='id')
    op.drop_constraint(op.f('trainingday_workout_id_fkey'), 'trainingday', type_='foreignkey')
    op.create_foreign_key(None, 'trainingday', 'workout', ['workout_id'], ['id'], ondelete='CASCADE')

    op.alter_column('exercise', 'exercise_id', new_column_name='id')

    op.drop_constraint(op.f('dayexercise_day_id_fkey'), 'dayexercise', type_='foreignkey')
    op.drop_constraint(op.f('dayexercise_exercise_id_fkey'), 'dayexercise', type_='foreignkey')
    op.drop_constraint(op.f('dayexercise_workout_id_fkey'), 'dayexercise', type_='foreignkey')
    op.create_foreign_key(None, 'dayexercise', 'workout', ['workout_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dayexercise', 'trainingday', ['day_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dayexercise', 'exercise', ['exercise_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('dayexercise', 'reps')
    op.drop_column('dayexercise', 'sets')

    op.alter_column('muscle', 'muscle_id', new_column_name='id')

    op.drop_constraint(op.f('muscle_antagonists_muscle_antagonist_id_fkey'), 'muscle_antagonists', type_='foreignkey')
    op.drop_constraint(op.f('muscle_antagonists_muscle_id_fkey'), 'muscle_antagonists', type_='foreignkey')
    op.create_foreign_key(None, 'muscle_antagonists', 'muscle', ['muscle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'muscle_antagonists', 'muscle', ['muscle_antagonist_id'], ['id'], ondelete='CASCADE')

    op.create_table('trainingdayhistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['trainingday.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainingdayhistory_day_id'), 'trainingdayhistory', ['day_id'], unique=False)
    op.create_table('exercisehistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('training_day_history_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(precision=2), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['training_day_history_id'], ['trainingdayhistory.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercisehistory_exercise_id'), 'exercisehistory', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercisehistory_training_day_history_id'), 'exercisehistory', ['training_day_history_id'], unique=False)
    op.create_index(op.f('ix_exercisehistory_user_id'), 'exercisehistory', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('rate', sa.REAL(), autoincrement=False, nullable=False, comment='Оценка от 0 до 10'))
    op.add_column('workout', sa.Column('workout_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'workout', type_='foreignkey')
    op.create_foreign_key(op.f('workout_user_id_fkey'), 'workout', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('workout', 'id')
    op.add_column('user', sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_column('user', 'id')
    op.add_column('trainingday', sa.Column('day_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'trainingday', type_='foreignkey')
    op.create_foreign_key(op.f('trainingday_workout_id_fkey'), 'trainingday', 'workout', ['workout_id'], ['workout_id'], ondelete='CASCADE')
    op.drop_column('trainingday', 'id')
    op.drop_constraint(None, 'muscle_antagonists', type_='foreignkey')
    op.drop_constraint(None, 'muscle_antagonists', type_='foreignkey')
    op.create_foreign_key(op.f('muscle_antagonists_muscle_id_fkey'), 'muscle_antagonists', 'muscle', ['muscle_id'], ['muscle_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('muscle_antagonists_muscle_antagonist_id_fkey'), 'muscle_antagonists', 'muscle', ['muscle_antagonist_id'], ['muscle_id'], ondelete='CASCADE')
    op.add_column('muscle', sa.Column('muscle_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('muscle', 'id')
    op.add_column('exercise', sa.Column('exercise_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('exercise', 'id')
    op.add_column('dayexercise', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dayexercise', sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dayexercise', type_='foreignkey')
    op.drop_constraint(None, 'dayexercise', type_='foreignkey')
    op.drop_constraint(None, 'dayexercise', type_='foreignkey')
    op.create_foreign_key(op.f('dayexercise_workout_id_fkey'), 'dayexercise', 'workout', ['workout_id'], ['workout_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('dayexercise_exercise_id_fkey'), 'dayexercise', 'exercise', ['exercise_id'], ['exercise_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('dayexercise_day_id_fkey'), 'dayexercise', 'trainingday', ['day_id'], ['day_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_exercisehistory_user_id'), table_name='exercisehistory')
    op.drop_index(op.f('ix_exercisehistory_training_day_history_id'), table_name='exercisehistory')
    op.drop_index(op.f('ix_exercisehistory_exercise_id'), table_name='exercisehistory')
    op.drop_table('exercisehistory')
    op.drop_index(op.f('ix_trainingdayhistory_day_id'), table_name='trainingdayhistory')
    op.drop_table('trainingdayhistory')
    # ### end Alembic commands ###
